/** @format */

import cabin1 from '../../assets/cabin-1.png';
import cabin2 from '../../assets/cabin-2.png';
import cabin3 from '../../assets/cabin-3.png';
import cabin4 from '../../assets/cabin-4.png';
import camper1 from '../../assets/camper-1.png';
import camper2 from '../../assets/camper-2.png';
import camper3 from '../../assets/camper-3.png';
import camper4 from '../../assets/camper-4.png';

export const cabinInfo = [
	{
		id: 'humming-bird-cabin',
		name: 'Humming Bird',
		description:
			'This cozy cabin is one of 8 cabins located on our 125 acres at Deer Creek Mountain Camp. The cabin sleeps 10 in bunk beds as shown in the pictures. Guests will provide their own bedding and toiletries for a nearby shower house. Cabin includes a gas grill, fridge, and microwave',
		capacity: 10,
		link: 'https://www.airbnb.com/rooms/27489287?source_impression_id=p3_1632114843_UATJPgjNjdOLDbMx&guests=1&adults=1',
		image: cabin1,
		color: '#E3A335',
		top: 53,
		left: 18,
	},
	{
		id: 'spruce-cabin',
		name: 'Spruce',
		description:
			'This cozy cabin is one of 8 cabins located on our 125 acres at Deer Creek Mountain Camp. The cabin sleeps 10 in bunk beds as shown in the pictures. Guests will provide their own bedding and toiletries for a nearby shower house. Cabin includes a gas grill, fridge, and microwave',
		capacity: 10,
		link: 'https://www.airbnb.com/rooms/27489932?source_impression_id=p3_1632115344_6QLhlkaojfkhLhdI&guests=1&adults=1',
		image: cabin2,
		color: '#F7669B',
		top: 56,
		left: 18,
	},
	{
		id: 'lark-cabin',
		name: 'Lark',
		description:
			'This cozy cabin is one of 8 cabins located on our 125 acres at Deer Creek Mountain Camp. The cabin sleeps 10 in bunk beds as shown in the pictures. Guests will provide their own bedding and toiletries for a nearby shower house. Cabin includes a gas grill, fridge, and microwave',
		capacity: 10,
		link: 'https://www.airbnb.com/rooms/27491680?source_impression_id=p3_1632115505_xTGGkA65SWX6%2B80M&guests=1&adults=1',
		image: cabin3,
		color: '#6691F4',
		top: 60,
		left: 17,
	},
	{
		id: 'moose-cabin',
		name: 'Moose',
		description:
			'This cozy cabin is one of 8 cabins located on our 125 acres at Deer Creek Mountain Camp. The cabin sleeps 10 in bunk beds as shown in the pictures. Guests will provide their own bedding and toiletries for a nearby shower house. Cabin includes a gas grill, fridge, and microwave',
		capacity: 10,
		link: 'https://www.airbnb.com/rooms/27980754?source_impression_id=p3_1632115583_dBIS6Ws3vPT7FPDY&guests=1&adults=1',
		image: cabin4,
		color: '#D0F766',
		top: 64,
		left: 19,
	},
	{
		id: 'bears-cave-cabin',
		name: "Bear's Cave",
		description:
			'There is parking for 1 vehicle below the apartment, and all other vehicles should be parked in the designated parking area below the gym. If you are a part of a wedding party, please check with the couple on where they would like you to park. The bedroom has a queen bed with an adjoining full bathroom. The lower room, where you walk in, has a full kitchen with gas range and full sized fridge. Water from every faucet on camp is safe to drink. Please be sure to wash all used dishes and utensils and either put them away or leave them in the drying rack.',
		capacity: 2,
		link: 'https://www.airbnb.com/rooms/27485332?source_impression_id=p3_1632115646_Hhk3sSTEhuojapfZ&guests=1&adults=1',
		image: cabin1,
		color: '#E3A335',
		top: 68,
		left: 13,
	},
	{
		id: 'crows-nest-cabin-1',
		name: "Crow's Nest Apt 1",
		description:
			'This cozy, natural lit apartment is located on 125 acres of beautiful mountain space. It is perfect for a couple or two single traveler to stay in comfort and enjoy all the beauty the outdoors has to offer, such as surrounding pine and aspen trees, and wildlife such as deer and chipmunks. The bathroom and showers for this apartment are located downstairs. The Women’s is at the front of the building and the Men’s is located in the back. Water from every faucet on camp is safe to drink. There is not WiFi available for guests',
		capacity: 2,
		link: 'https://www.airbnb.com/rooms/30952771?source_impression_id=p3_1632163925_nj1%2B%2FmKu%2FDiKcXzh',
		image: cabin2,
		color: '#F7669B',
		top: 63,
		left: 13,
	},
	{
		id: 'crows-nest-cabin-2',
		name: "Crow's Nest Apt 2",
		description:
			'This cozy, natural lit apartment is located on 125 acres of beautiful mountain space. It is perfect for a couple or two single traveler to stay in comfort and enjoy all the beauty the outdoors has to offer, such as surrounding pine and aspen trees, and wildlife such as deer and chipmunks. The bathroom and showers for this apartment are located downstairs. The Women’s is at the front of the building and the Men’s is located in the back. Water from every faucet on camp is safe to drink. There is not WiFi available for guests',
		capacity: 2,
		link: 'https://www.airbnb.com/rooms/30955078?source_impression_id=p3_1632163934_gd1oU1pECe8okPpz',
		image: cabin3,
		color: '#6691F4',
		top: 63,
		left: 13,
	},
	{
		id: 'crows-nest-cabin-3',
		name: "Crow's Nest Apt 3",
		description:
			'This cozy, natural lit apartment is located on 125 acres of beautiful mountain space. It is perfect for a couple or two single traveler to stay in comfort and enjoy all the beauty the outdoors has to offer, such as surrounding pine and aspen trees, and wildlife such as deer and chipmunks. The bathroom and showers for this apartment are located downstairs. The Women’s is at the front of the building and the Men’s is located in the back. Water from every faucet on camp is safe to drink. There is not WiFi available for guests',
		capacity: 2,
		image: cabin4,
		link: 'https://www.airbnb.com/rooms/30956997/photos?source_impression_id=p3_1632163935_X1udqgTsta6l6HBW',
		color: '#D0F766',
		top: 63,
		left: 13,
	},
	{
		id: 'crows-nest-cabin-4',
		name: "Crow's Nest Apt 4",
		description:
			'This cozy, natural lit apartment is located on 125 acres of beautiful mountain space. It is perfect for a couple to stay in comfort and enjoy all the beauty the outdoors has to offer, such as surrounding pine and aspen trees, and wildlife such as deer and chipmunks. There is a bathroom in unit. Water from every faucet on camp is safe to drink. There is not WiFi available for guests',
		capacity: 2,
		link: 'https://www.airbnb.com/rooms/27983954?source_impression_id=p3_1632163918_zeJBTUARRyz64vuj',
		image: cabin1,
		color: '#E3A335',
		top: 63,
		left: 13,
	},
	{
		id: 'crows-nest-cabin-5',
		name: "Crow's Nest Apt 5",
		description:
			'This cozy, natural lit apartment is located on 125 acres of beautiful mountain space. It is perfect for a couple to stay in comfort and enjoy all the beauty the outdoors has to offer, such as surrounding pine and aspen trees, and wildlife such as deer and chipmunks. There is a bathroom in unit. Water from every faucet on camp is safe to drink. There is not WiFi available for guests',
		capacity: 2,
		image: cabin2,
		link: 'https://www.airbnb.com/rooms/27984526?source_impression_id=p3_1632163930_C%2Fy%2FDtLbu5dybWtd',
		color: '#F7669B',
		top: 63,
		left: 13,
	},
	{
		id: 'black-bear-1-cabin',
		name: 'Black Bear 1',
		description:
			'This home, with natural light from the Eastern facing windows, is comfortable and cozy for a family or group of friends. It has 6 single beds (bunk style) and one queen bed, shared between two rooms. Black Bear sits on 125 acres of gorgeous mountain space perfect for enjoying the outdoors and everything it has to offer. It has a full kitchen, supplied with everything you could need to cook meals for the group. Water from every faucet at camp is safe to drink. There is no wifi available to guests.',
		capacity: 8,
		link: 'https://www.airbnb.com/rooms/30983763?source_impression_id=p3_1632116155_fIuBQib0fFuVq5qJ&guests=1&adults=1',
		image: cabin3,
		color: '#6691F4',
		top: 71,
		left: 16,
	},
	{
		id: 'black-bear-2-cabin',
		name: 'Black Bear 2',
		description:
			'With one queen bed, this cozy two room apartment is perfect for a couple or small family to enjoy the 125 acre camp facility available year round at Deer Creek Mountain Camp or as part of larger group rentals.',
		capacity: 2,
		link: 'https://www.airbnb.com/rooms/48132023?source_impression_id=p3_1632116438_22mRKHZKszuPiOEH&guests=1&adults=1',
		image: cabin4,
		color: '#D0F766',
		top: 68,
		left: 16,
	},
	{
		id: 'pine-cabin',
		name: 'Pine',
		description:
			'This cozy cabin is one of 8 cabins located on our 125 acres at Deer Creek Mountain Camp. The cabin sleeps 10 in bunk beds as shown in the pictures. Guests will provide their own bedding and toiletries for a nearby shower house. Cabin includes a gas grill, fridge, and microwave',
		capacity: 10,
		link: 'https://www.airbnb.com/rooms/37052122?source_impression_id=p3_1632162777_cWcUuAh93o0yRApg&guests=1&adults=1',
		image: cabin1,
		color: '#E3A335',
		top: 85,
		left: 18,
	},
	{
		id: 'jackalope-cabin',
		name: 'Jackalope',
		description:
			'This cozy cabin is one of 8 cabins located on our 125 acres at Deer Creek Mountain Camp. The cabin sleeps 10 in bunk beds as shown in the pictures. Guests will provide their own bedding and toiletries for a nearby shower house. Cabin includes a gas grill, fridge, and microwave',
		capacity: 10,
		link: 'https://www.airbnb.com/rooms/37051111?source_impression_id=p3_1632162859_fooEpbL5BeWWH03Q&guests=1&adults=1',
		image: cabin2,
		color: '#F7669B',
		top: 85,
		left: 18,
	},
	{
		id: 'arapahoe-cabin',
		name: 'Arapahoe',
		description:
			'This lodge fits 24 people, with three bedrooms that each have 4 bunk beds, a full kitchen stocked with cookware and utensils, a living room, a wood burning stove, and two bathrooms that each have two showers. Please be aware the cabin does not have bedding or toiletries provided. Water from every faucet on camp is safe to drink. There is not WiFi access on camp for guest use',
		capacity: 24,
		link: 'https://www.airbnb.com/rooms/30959681?source_impression_id=p3_1632162919_IgSowexqi0U9coMt&guests=1&adults=1',
		image: cabin3,
		color: '#6691F4',
		top: 85,
		left: 18,
	},
	{
		id: 'sasquach-cabin',
		name: 'Sasquach',
		description:
			'This cozy cabin is one of 8 cabins located on our 125 acres at Deer Creek Mountain Camp. The cabin sleeps 10 in bunk beds as shown in the pictures. Guests will provide their own bedding and toiletries for a nearby shower house. Cabin includes a gas grill, fridge, and microwave',
		capacity: 10,
		link: 'airbnb.com/rooms/37053401?source_impression_id=p3_1632162654_Mdqd32o%2FEF1SbqzP&guests=1&adults=1',
		image: cabin4,
		color: '#D0F766',
		top: 85,
		left: 18,
	},
	{
		id: 'aspen-cabin',
		name: 'Aspen',
		description:
			'This cozy cabin is one of 8 cabins located on our 125 acres at Deer Creek Mountain Camp. The cabin sleeps 10 in bunk beds as shown in the pictures. Guests will provide their own bedding and toiletries for a nearby shower house. Cabin includes a gas grill, fridge, and microwave',
		capacity: 10,
		link: 'https://www.airbnb.com/rooms/36794977?source_impression_id=p3_1632163793_FbV6QPb%2BgH6uigwE&guests=1&adults=1',
		image: cabin1,
		color: '#E3A335',
		top: 85,
		left: 18,
	},
	{
		id: 'rv-1',
		name: 'RV #1',
		description: '',
		capacity: 1,
		image: camper2,
		color: '#F7669B',
		top: 85,
		left: 18,
	},
	{
		id: 'rv-2',
		name: 'RV #2',
		description: '',
		capacity: 1,
		image: camper3,
		color: '#6691F4',
		top: 85,
		left: 18,
	},
	{
		id: 'rv-3',
		name: 'RV #3',
		description: '',
		capacity: 1,
		image: camper4,
		color: '#D0F766',
		top: 85,
		left: 18,
	},
	{
		id: 'rv-4',
		name: 'RV #4',
		description: '',
		capacity: 1,
		image: camper1,
		color: '#E3A335',
		top: 85,
		left: 18,
	},
	{
		id: 'rv-5',
		name: 'RV #5',
		description: '',
		capacity: 1,
		image: camper2,
		color: '#F7669B',
		top: 85,
		left: 18,
	},
	{
		id: 'rv-6',
		name: 'RV #6',
		description: '',
		capacity: 1,
		image: camper3,
		color: '#6691F4',
		top: 85,
		left: 18,
	},
];
